### PR TITLE
update to adal 5.0.1

### PR DESCRIPTION
**Pull request by jennyf19**
@jmprieur was testing for the 5.0.1 release and found it helpful to add in msal v4 as a separate project, but not sure if this is something you want to do here or not. thought i'd make a PR anyway. was going to rename the v3 project, but since we have to maintain the major versions, thought it better to make a separate v4 one. lmk how you'd like to proceed. can also just update the packages.

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM.
As we are here, we could use the Async methods in MSAL 4, and leverage Async I/O methods?
And the README and .bat file needs to be updated

Let's discuss what we want to do.

**Comment by jmprieur** [comment]
@jennyf19 : do you expect something else from me?

**Comment by jennyf19** [comment]
@jmprieur I haven't had time to do the things you mentioned above...do you want me to merge or wait? I won't have time this week.

**Comment by jmprieur** [comment]
@jennyf19 : I can take them, no worries :)

**Comment by jennyf19** [comment]
ok...so merge or leave as-is and you'll merge into here? @jmprieur and..thank you.

**Comment by jmprieur** [comment]
yes, go ahead, @jennyf19

**Pull request merged**
